name: pyscenic_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Use Python 3.10 so python-igraph=0.10.2 is compatible
  - python=3.10
  - numpy=1.22
  - multicore-tsne 
  
  # Basic conda-managed packages
  - pip
  - pandas=1.5.1
  - scikit-learn=1.1.3
  - python-igraph=0.10.2
  - louvain=0.8.1       # works with igraph>=0.10
  - leidenalg=0.9.0     # requires igraph>=0.10.1
  - cairo
  - scanpy=1.9.1
  - jupyter
  - openjdk

  # All other packages from your pip-freeze
  - pip:
    - pySCENIC==0.12.1
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - ansiwrap==0.8.4
    - arboreto==0.1.6
    - asttokens==2.1.0
    - async-timeout==4.0.2
    - attrs==22.1.0 
    - backcall==0.2.0
    - bokeh
    - boltons==21.0.0
    - certifi==2022.9.24
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - contourpy==1.0.6
    - ctxcore==0.2.0
    - cycler==0.11.0
    - cytoolz==0.12.0
    - dask==2022.11.1
    - debugpy==1.6.3
    - decorator==5.1.1
    - dill==0.3.6
    - distributed
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - fonttools==4.38.0
    - frozendict==2.3.4
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - h5py==3.7.0
    - HeapDict==1.0.1
    - idna==3.4
    - interlap==0.2.7
    - ipykernel
    - ipython==8.6.0
    - jedi==0.18.1
    - Jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.0
    - jupyter_client
    - jupyterlab
    - jupyter_server
    - jupyterlab_server
    - jupyter_core
    - kiwisolver==1.4.4
    - llvmlite==0.39.1
    - locket==1.0.0
    - loompy==3.0.7
    - MarkupSafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - msgpack==1.0.4
    - multidict==6.0.2
    - multiprocessing-on-dill==3.5.0a4
    - natsort==8.2.0
    - nbclient==0.7.0
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.8.8
    - numba==0.56.4
    - numexpr==2.8.4
    - numpy-groupies==0.9.20
    - packaging==21.3
    - papermill==2.3.4
    - parso==0.8.3
    - partd==1.3.0
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - Pillow==9.3.0
    - platformdirs==2.5.4
    - prompt-toolkit==3.0.32
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==10.0.0
    - pycparser==2.21
    - Pygments==2.13.0
    - pynndescent==0.5.8
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - PyYAML==6.0
    - pyzmq==24.0.1
    - requests==2.28.1
    - scipy==1.9.3
    - seaborn==0.12.1
    - session-info==1.0.0
    - six==1.16.0
    - sortedcontainers==2.4.0
    - stack-data==0.6.1
    - statsmodels==0.13.5
    - stdlib-list==0.8.0
    - tblib==1.7.0
    - tenacity==8.1.0
    - tornado
    - texttable==1.6.5
    - textwrap3==0.9.2
    - threadpoolctl==3.1.0
    - toolz==0.12.0
    - tqdm==4.64.1
    - traitlets==5.5.0
    - typing_extensions==4.4.0
    - umap-learn==0.5.3
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - yarl==1.8.1
    - zict==2.2.0