name: pyscenic_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - numba
  - pyarrow
  - python-igraph
  - louvain
  - leidenalg
  - cairo
  - scanpy
  - jupyter
  - openjdk
  - pip:
    - pySCENIC==0.12.1
